### ISSUE TITLE
Task 2, Step 6

### ISSUE THREAD

**Issue by timsander1** [solliancenet/cosmos-db-scenario-based-labs#22]
Instructions say to copy configuration settings from lab setup script output but Cosmos DB Key is blank from when I ran lab setup script earlier in the lab.

**Comment by givenscj** [comment]
Unfortunately I would need to see this one as it won't repo on my side.  Let me know when you have a chance to show me your environment.

**Comment by givenscj** [comment]
Closing.  Create a new issue in the MSFT repo version if you are still having issues.
