### ISSUE TITLE
[Retail Lab] Before HOL: Task 3 deploy to other regions

### ISSUE THREAD

**Issue by falloutxAY** [solliancenet/cosmos-db-scenario-based-labs#23]
Can the participants deploy this to other regions in the [setup](https://github.com/solliancenet/cosmos-db-scenario-based-labs/blob/master/Retail/Before%20the%20HOL%20-%20Cosmos%20DB%20scenario-based%20labs%20-%20Retail.md#task-3-deploy-resources-to-azure)? 
`$region = XXXXXXX`

**Comment by givenscj** [comment]
This was updated in the ARM templates to allow any region.  Only a few have been tested.  Change made in MSFT repo.
