### ISSUE TITLE
[Retail Lab] Before HOL (Task 3, Step 3)- Set up execution policies

### ISSUE THREAD

**Issue by falloutxAY** [solliancenet/cosmos-db-scenario-based-labs#24]
Some participants may not have the rights to execute this and will have the below error when you try to execute the deploy.ps1 (Press F5).

> You cannot run this script 
on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at 
https:/go.microsoft.com/fwlink/?LinkID=135170.

Suggest to put the follow note:
1) Run PowerShell ISE in Administrator mode
2) Run the below command
`Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass`
3) Exeute deploy.ps1 (Press F5)

**Comment by givenscj** [comment]
Added.
