### ISSUE TITLE
[Retail Lab] Before HOL (Task 3 Step 3) - Issue with deployment

### ISSUE THREAD

**Issue by falloutxAY** [solliancenet/cosmos-db-scenario-based-labs#25]
Multiple issues faced when running deploy,ps1

1) Received this error 

> Deploying [labdeploy5.json] - Please wait
Deploying [labdeploy5.json] finished with status Succeeded
Deploying [labdeploy.json] - Please wait
az : ERROR: Deployment failed. Correlation ID: 83fdcdeb-697f-454a-bfe3-e911c99b08ab. {
At C:\Users\ansyeo\Documents\cosmos-db-scenario-based-labs\Retail\deploy\deploy.ps1:62 char:25
\+ ... $result = $(az group deployment create --name $deployId --resource-gr ...
\+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    \+ CategoryInfo          : NotSpecified: (ERROR: Deployme...e911c99b08ab. {:String) [], RemoteException
    \+ FullyQualifiedErrorId : NativeCommandError
>  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'Microsoft.Web/sites/s2webors6q2uxate42' under resource group 'ayy123_s2_retail' was not found."
  }
}
Deploying [labdeploy.json] finished with status Failed
Deployment failed: Please enter the suffix that was created for the resource group: ors6q2uxate42
Deploying [labdeploy4.json] - Please wait

2) It also asked for the suffix that was created for the resource group. Should include the instructions on how to obtain it. 

3) Multiply key vault issues when is trying to set key vault values.
[retailcosmoslab_issue.txt](https://github.com/solliancenet/cosmos-db-scenario-based-labs/files/3706019/retailcosmoslab_issue.txt)

**Comment by givenscj** [comment]
This could be any number of things.  We have seen certain internal subscriptions error due to limits or throttles.  You may need to debug further by looking at the deployment logs and letting us know what you might be hitting.

**Comment by givenscj** [comment]
Adding a FAQ to help with misc issues like this.  Will be added in the MSFT repo.
