### ISSUE TITLE
[Retail Lab] Before HOL (Task 3: Deploy resources to Azure)

### ISSUE THREAD

**Issue by brpham** [solliancenet/cosmos-db-scenario-based-labs#37]
I received below error. I had to build the Visual Studio solutions prior to running the  $githubdir/Retail/deploy/deploy.ps1 PowerShell script to fix the problem. Maybe include this note in instructions.
===================================

Saving app settings to web application
Saving app settings to func app...
Saving app settings to Visual Studio solutions (starter and solution)
get-content : Cannot find path 
'C:\Users\Administrator\Documents\LABS\CosmosDB\DEMO\cosmos-db-scenario-based-labs-master\cosmos-db-scenario-based-labs-master\Retail\starter\Data 
Import\bin\Debug\MovieDataImport.exe.config' because it does not exist.
At C:\Users\Administrator\Documents\LABS\CosmosDB\DEMO\cosmos-db-scenario-based-labs-master\cosmos-db-scenario-based-labs-master\Retail\deploy\depl
oy.ps1:95 char:17
+     [xml]$xml = get-content $filepath;

**Comment by givenscj** [comment]
I added code to actually do an MSBuild of the projects in demo mode.  Over in MSFT version of repo.
