### ISSUE TITLE
[Retail Lab] Before HOL (Task 3: Deploy resources to Azure)

### ISSUE THREAD

**Issue by brpham** [solliancenet/cosmos-db-scenario-based-labs#38]
Setting key vault values...
az : ERROR: az keyvault secret set: error: argument --vault-name: expected one argument
At C:\cosmos-db-scenario-based-labs-master\Retail\deploy\deploy.ps1:666 char:10
+ $res = $(az keyvault secret set --vault-name $keyvault.Name --name "p ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: az keyva...ed one argument:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
usage: az keyvault secret set [-h] [--verbose] [--debug]
                              [--output {json,jsonc,table,tsv,yaml,none}]
                              [--query JMESPATH]
                              [--subscription _SUBSCRIPTION] --vault-name NAME
                              --name SECRET_NAME [--value VALUE]
                              [--tags [TAGS [TAGS ...]]]
                              [--description CONTENT_TYPE]
                              [--disabled [{true,false}]] [--expires EXPIRES]
                              [--not-before NOT_BEFORE] [--file FILE_PATH]
                              [--encoding {utf-8,utf-16le,utf-16be,ascii,base64,hex}]
az : ERROR: az keyvault secret set: error: argument --vault-name: expected one argument
At C:\cosmos-db-scenario-based-labs-master\Retail\deploy\deploy.ps1:667 char:10
+ $res = $(az keyvault secret set --vault-name $keyvault.Name --name "A ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: az keyva...ed one argument:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
usage: az keyvault secret set [-h] [--verbose] [--debug]
                              [--output {json,jsonc,table,tsv,yaml,none}]
                              [--query JMESPATH]
                              [--subscription _SUBSCRIPTION] --vault-name NAME
                              --name SECRET_NAME [--value VALUE]
                              [--tags [TAGS [TAGS ...]]]
                              [--description CONTENT_TYPE]
                              [--disabled [{true,false}]] [--expires EXPIRES]
                              [--not-before NOT_BEFORE] [--file FILE_PATH]
                              [--encoding {utf-8,utf-16le,utf-16be,ascii,base64,hex}]
az : ERROR: az keyvault secret set: error: argument --vault-name: expected one argument
At C:\cosmos-db-scenario-based-labs-master\Retail\deploy\deploy.ps1:669 char:10
+ $res = $(az keyvault secret set --vault-name $keyvault.Name --name "f ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: az keyva...ed one argument:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
usage: az keyvault secret set [-h] [--verbose] [--debug]
                              [--output {json,jsonc,table,tsv,yaml,none}]
                              [--query JMESPATH]
                              [--subscription _SUBSCRIPTION] --vault-name NAME
                              --name SECRET_NAME [--value VALUE]
                              [--tags [TAGS [TAGS ...]]]
                              [--description CONTENT_TYPE]
                              [--disabled [{true,false}]] [--expires EXPIRES]
                              [--not-before NOT_BEFORE] [--file FILE_PATH]
                              [--encoding {utf-8,utf-16le,utf-16be,ascii,base64,hex}]
az : ERROR: az keyvault secret set: error: argument --vault-name: expected one argument
At C:\cosmos-db-scenario-based-labs-master\Retail\deploy\deploy.ps1:673 char:10
+ $res = $(az keyvault secret set --vault-name $keyvault.Name --name "f ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: az keyva...ed one argument:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
usage: az keyvault secret set [-h] [--verbose] [--debug]
                              [--output {json,jsonc,table,tsv,yaml,none}]
                              [--query JMESPATH]
                              [--subscription _SUBSCRIPTION] --vault-name NAME
                              --name SECRET_NAME [--value VALUE]
                              [--tags [TAGS [TAGS ...]]]
                              [--description CONTENT_TYPE]
                              [--disabled [{true,false}]] [--expires EXPIRES]
                              [--not-before NOT_BEFORE] [--file FILE_PATH]
                              [--encoding {utf-8,utf-16le,utf-16be,ascii,base64,hex}]
az : ERROR: az keyvault secret set: error: argument --vault-name: expected one argument
At C:\cosmos-db-scenario-based-labs-master\Retail\deploy\deploy.ps1:677 char:10
+ $res = $(az keyvault secret set --vault-name $keyvault.Name --name "d ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: az keyva...ed one argument:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
usage: az keyvault secret set [-h] [--verbose] [--debug]
                              [--output {json,jsonc,table,tsv,yaml,none}]
                              [--query JMESPATH]
                              [--subscription _SUBSCRIPTION] --vault-name NAME
                              --name SECRET_NAME [--value VALUE]
                              [--tags [TAGS [TAGS ...]]]
                              [--description CONTENT_TYPE]
                              [--disabled [{true,false}]] [--expires EXPIRES]
                              [--not-before NOT_BEFORE] [--file FILE_PATH]
                              [--encoding {utf-8,utf-16le,utf-16be,ascii,base64,hex}]
az : ERROR: az keyvault secret set: error: argument --vault-name: expected one argument
At C:\cosmos-db-scenario-based-labs-master\Retail\deploy\deploy.ps1:681 char:10
+ $res = $(az keyvault secret set --vault-name $keyvault.Name --name "C ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: az keyva...ed one argument:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
usage: az keyvault secret set [-h] [--verbose] [--debug]
                              [--output {json,jsonc,table,tsv,yaml,none}]
                              [--query JMESPATH]
                              [--subscription _SUBSCRIPTION] --vault-name NAME
                              --name SECRET_NAME [--value VALUE]
                              [--tags [TAGS [TAGS ...]]]
                              [--description CONTENT_TYPE]
                              [--disabled [{true,false}]] [--expires EXPIRES]
                              [--not-before NOT_BEFORE] [--file FILE_PATH]
                              [--encoding {utf-8,utf-16le,utf-16be,ascii,base64,hex}]
az : ERROR: az keyvault secret set: error: argument --vault-name: expected one argument
At C:\cosmos-db-scenario-based-labs-master\Retail\deploy\deploy.ps1:685 char:10
+ $res = $(az keyvault secret set --vault-name $keyvault.Name --name "d ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: az keyva...ed one argument:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
usage: az keyvault secret set [-h] [--verbose] [--debug]
                              [--output {json,jsonc,table,tsv,yaml,none}]
                              [--query JMESPATH]
                              [--subscription _SUBSCRIPTION] --vault-name NAME
                              --name SECRET_NAME [--value VALUE]
                              [--tags [TAGS [TAGS ...]]]
                              [--description CONTENT_TYPE]
                              [--disabled [{true,false}]] [--expires EXPIRES]
                              [--not-before NOT_BEFORE] [--file FILE_PATH]
                              [--encoding {utf-8,utf-16le,utf-16be,ascii,base64,hex}]
az : ERROR: az keyvault secret set: error: argument --vault-name: expected one argument
At C:\cosmos-db-scenario-based-labs-master\Retail\deploy\deploy.ps1:689 char:10
+ $res = $(az keyvault secret set --vault-name $keyvault.Name --name "d ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: az keyva...ed one argument:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
usage: az keyvault secret set [-h] [--verbose] [--debug]
                              [--output {json,jsonc,table,tsv,yaml,none}]
                              [--query JMESPATH]
                              [--subscription _SUBSCRIPTION] --vault-name NAME
                              --name SECRET_NAME [--value VALUE]
                              [--tags [TAGS [TAGS ...]]]
                              [--description CONTENT_TYPE]
                              [--disabled [{true,false}]] [--expires EXPIRES]
                              [--not-before NOT_BEFORE] [--file FILE_PATH]
                              [--encoding {utf-8,utf-16le,utf-16be,ascii,base64,hex}]
az : ERROR: az keyvault secret set: error: argument --vault-name: expected one argument
At C:\cosmos-db-scenario-based-labs-master\Retail\deploy\deploy.ps1:693 char:10
+ $res = $(az keyvault secret set --vault-name $keyvault.Name --name "e ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: az keyva...ed one argument:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
usage: az keyvault secret set [-h] [--verbose] [--debug]
                              [--output {json,jsonc,table,tsv,yaml,none}]
                              [--query JMESPATH]
                              [--subscription _SUBSCRIPTION] --vault-name NAME
                              --name SECRET_NAME [--value VALUE]
                              [--tags [TAGS [TAGS ...]]]
                              [--description CONTENT_TYPE]
                              [--disabled [{true,false}]] [--expires EXPIRES]
                              [--not-before NOT_BEFORE] [--file FILE_PATH]
                              [--encoding {utf-8,utf-16le,utf-16be,ascii,base64,hex}]
az : ERROR: az keyvault secret set: error: argument --vault-name: expected one argument
At C:\cosmos-db-scenario-based-labs-master\Retail\deploy\deploy.ps1:697 char:10
+ $res = $(az keyvault secret set --vault-name $keyvault.Name --name "e ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: az keyva...ed one argument:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
usage: az keyvault secret set [-h] [--verbose] [--debug]
                              [--output {json,jsonc,table,tsv,yaml,none}]
                              [--query JMESPATH]
                              [--subscription _SUBSCRIPTION] --vault-name NAME
                              --name SECRET_NAME [--value VALUE]
                              [--tags [TAGS [TAGS ...]]]
                              [--description CONTENT_TYPE]
                              [--disabled [{true,false}]] [--expires EXPIRES]
                              [--not-before NOT_BEFORE] [--file FILE_PATH]
                              [--encoding {utf-8,utf-16le,utf-16be,ascii,base64,hex}]
az : ERROR: az keyvault secret set: error: argument --vault-name: expected one argument
At C:\cosmos-db-scenario-based-labs-master\Retail\deploy\deploy.ps1:701 char:10
+ $res = $(az keyvault secret set --vault-name $keyvault.Name --name "m ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: az keyva...ed one argument:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
usage: az keyvault secret set [-h] [--verbose] [--debug]
                              [--output {json,jsonc,table,tsv,yaml,none}]
                              [--query JMESPATH]
                              [--subscription _SUBSCRIPTION] --vault-name NAME
                              --name SECRET_NAME [--value VALUE]
                              [--tags [TAGS [TAGS ...]]]
                              [--description CONTENT_TYPE]
                              [--disabled [{true,false}]] [--expires EXPIRES]
                              [--not-before NOT_BEFORE] [--file FILE_PATH]
                              [--encoding {utf-8,utf-16le,utf-16be,ascii,base64,hex}]
az : ERROR: az keyvault secret set: error: argument --vault-name: expected one argument
At C:\cosmos-db-scenario-based-labs-master\Retail\deploy\deploy.ps1:705 char:10
+ $res = $(az keyvault secret set --vault-name $keyvault.Name --name "L ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: az keyva...ed one argument:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
usage: az keyvault secret set [-h] [--verbose] [--debug]
                              [--output {json,jsonc,table,tsv,yaml,none}]
                              [--query JMESPATH]
                              [--subscription _SUBSCRIPTION] --vault-name NAME
                              --name SECRET_NAME [--value VALUE]
                              [--tags [TAGS [TAGS ...]]]
                              [--description CONTENT_TYPE]
                              [--disabled [{true,false}]] [--expires EXPIRES]
                              [--not-before NOT_BEFORE] [--file FILE_PATH]
                              [--encoding {utf-8,utf-16le,utf-16be,ascii,base64,hex}]
az : ERROR: az keyvault secret set: error: argument --vault-name: expected one argument
At C:\cosmos-db-scenario-based-labs-master\Retail\deploy\deploy.ps1:709 char:10
+ $res = $(az keyvault secret set --vault-name $keyvault.Name --name "R ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: az keyva...ed one argument:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
usage: az keyvault secret set [-h] [--verbose] [--debug]
                              [--output {json,jsonc,table,tsv,yaml,none}]
                              [--query JMESPATH]
                              [--subscription _SUBSCRIPTION] --vault-name NAME
                              --name SECRET_NAME [--value VALUE]
                              [--tags [TAGS [TAGS ...]]]
                              [--description CONTENT_TYPE]
                              [--disabled [{true,false}]] [--expires EXPIRES]
                              [--not-before NOT_BEFORE] [--file FILE_PATH]
                              [--encoding {utf-8,utf-16le,utf-16be,ascii,base64,hex}]
Saving app settings to web application

**Comment by givenscj** [comment]
This will occur when the values are blank.  If your previous deployment steps failed, this will also fail gloriously.  Some of the values will not have a value so the error would be ok in that instance.  We could add a function that checks for a blank value and doesn't confuse the user.

**Comment by givenscj** [comment]
Added method to check for blank value so as to not show any errors.  This is over in the Microsoft version of this repo.
